name: OpenaiModeration
authors: [Paneddo, MegaPVP]
description: Chat Moderation plugin based on OpenAI
version: '${project.version}'
main: it.paneddo.openaimoderation.OpenaiModeration
api-version: 1.19
